// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs23ijtC-EGsIjf1gjJuSptpQoYDjwjSI',
    appId: '1:857238517551:web:973686945eb3fc4ac153da',
    messagingSenderId: '857238517551',
    projectId: 'news-share-f7c71',
    authDomain: 'news-share-f7c71.firebaseapp.com',
    storageBucket: 'news-share-f7c71.firebasestorage.app',
    measurementId: 'G-WE7WG0LVF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtQ1OdOTL6Ee0Wpw3qq8CjfMDHSz7gBKw',
    appId: '1:857238517551:android:91c0b4b7ca4bc987c153da',
    messagingSenderId: '857238517551',
    projectId: 'news-share-f7c71',
    storageBucket: 'news-share-f7c71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRD5hud9vnnOU9r6y-xYg9S6oV6jW0V1w',
    appId: '1:857238517551:ios:6b97125e364d2599c153da',
    messagingSenderId: '857238517551',
    projectId: 'news-share-f7c71',
    storageBucket: 'news-share-f7c71.firebasestorage.app',
    iosBundleId: 'com.example.newsShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRD5hud9vnnOU9r6y-xYg9S6oV6jW0V1w',
    appId: '1:857238517551:ios:6b97125e364d2599c153da',
    messagingSenderId: '857238517551',
    projectId: 'news-share-f7c71',
    storageBucket: 'news-share-f7c71.firebasestorage.app',
    iosBundleId: 'com.example.newsShare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs23ijtC-EGsIjf1gjJuSptpQoYDjwjSI',
    appId: '1:857238517551:web:fbd0a8f56be4ab58c153da',
    messagingSenderId: '857238517551',
    projectId: 'news-share-f7c71',
    authDomain: 'news-share-f7c71.firebaseapp.com',
    storageBucket: 'news-share-f7c71.firebasestorage.app',
    measurementId: 'G-JMHXWKFSQQ',
  );

}